FROM ${IMAGE_NAME}

# Secrets injected at runtime
ENV GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/credentials.json
ENV GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}

# Get the source.
RUN git clone --depth 1 https://github.com/GoogleCloudPlatform/google-cloud-python.git
WORKDIR google-cloud-python

# Install tox for running the system tests
RUN pip install --upgrade tox

# Run Python 2.7, 3.5 system tests
ENTRYPOINT ["tox", "-e", "system-tests,system-tests3"]
