.PHONY: all
all:
	../../ext_run.sh -i "${IMAGE_NAME}" -c virtualenv_default.yaml -v
	../../ext_run.sh -i "${IMAGE_NAME}" -c virtualenv_python34.yaml -v
	../../ext_run.sh -i "${IMAGE_NAME}" -c virtualenv_python35.yaml -v
